# Generated by Django 2.1.5 on 2023-04-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='historiasClinicas.HistoriaClinica')),
            ],
        ),
    ]
