# Generated by Django 4.1.6 on 2023-03-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('triage', models.CharField(max_length=100)),
            ],
        ),
    ]
