# Generated by Django 4.1.6 on 2023-03-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='triage',
        ),
    ]
