# Generated by Django 4.1.6 on 2023-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_edad_remove_paciente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='triage',
            field=models.CharField(default='', max_length=100),
        ),
    ]
