# Generated by Django 4.1.6 on 2023-04-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
