# Generated by Django 2.1.5 on 2023-04-14 13:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('enfermedades', jsonfield.fields.JSONField(default=list)),
                ('tratamientos', jsonfield.fields.JSONField(default=list)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pacientes.Paciente')),
            ],
        ),
    ]
