# Generated by Django 4.1.6 on 2023-03-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='enfermedades',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tratamientos',
            field=models.CharField(max_length=100),
        ),
    ]
