# Generated by Django 4.1.6 on 2023-03-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0002_alter_historiaclinica_enfermedades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='tratamientos',
        ),
    ]
