# Generated by Django 4.1.6 on 2023-03-17 23:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasClinicas', '0003_remove_historiaclinica_enfermedades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='enfermedades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tratamientos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
