# Generated by Django 2.1.5 on 2023-04-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=100)),
                ('fechaNacimiento', models.DateField(blank=True, default=None, null=True)),
                ('triage', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
